version: '3.3'
services:
  wine:
    build: .
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority
      - ${HOME}/.vdrift:/root/.vdrift
      # - ./star:/root/star
    devices:
      - /dev/input:/dev/input
      - /dev/snd:/dev/snd
      - /dev/dri:/dev/dri
    command: >
      bash -c "
        wine /root/air.exe -silent &&
        wine /root/star/star_liner_app/star_liner_app.exe
      "